version: 2
jobs:
  build:
    docker: 
    # the primary container, where your job's commands are run
    # uses python 3.6.6 but then tox will also use its own version specifications inside virtualenv
      - image: circleci/python:3.6.6

    steps:
      - checkout # check out the code in the project directory
      - run: # install and activate virtual environment with pip
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install tox
      - run: # run tests
          command: |
            . venv/bin/activate
            tox